export const permissions = [
  "dashboard.view",
  "routers.view",
  "routers.create",
  "routers.update",
  "routers.delete",
  "routers.discover",
  "routers.testConnection",
  "routers.health.view",
  "configuration.view",
  "configuration.plan",
  "configuration.requestChange",
  "configuration.validate",
  "ai.ask",
  "ai.plan",
  "ai.securityReview",
  "ai.recommendFix",
  "change.view",
  "change.create",
  "change.approve",
  "change.reject",
  "change.execute",
  "change.rollback",
  "backup.view",
  "backup.create",
  "backup.restore",
  "backup.schedule",
  "monitoring.view",
  "monitoring.alerts.manage",
  "security.view",
  "security.audit",
  "security.secrets.manage",
  "reports.view",
  "reports.export",
  "admin.users.manage",
  "admin.roles.manage",
  "admin.settings.manage",
  "audit.view",
  "profile.view"
] as const;

export type Permission = (typeof permissions)[number];

export const rolePermissions: Record<string, Permission[]> = {
  "Super Administrator": [...permissions],
  "Network Administrator": permissions.filter((permission) => !permission.startsWith("admin.roles")),
  "Network Engineer": [
    "dashboard.view",
    "routers.view",
    "routers.create",
    "routers.update",
    "routers.discover",
    "routers.testConnection",
    "routers.health.view",
    "configuration.view",
    "configuration.plan",
    "configuration.requestChange",
    "configuration.validate",
    "ai.ask",
    "ai.plan",
    "change.view",
    "change.create",
    "backup.view",
    "backup.create",
    "monitoring.view",
    "reports.view",
    "profile.view"
  ],
  "Security Administrator": [
    "dashboard.view",
    "routers.view",
    "configuration.view",
    "ai.ask",
    "ai.securityReview",
    "change.view",
    "backup.view",
    "monitoring.view",
    "security.view",
    "security.audit",
    "security.secrets.manage",
    "reports.view",
    "reports.export",
    "audit.view",
    "profile.view"
  ],
  Helpdesk: ["dashboard.view", "routers.view", "routers.testConnection", "monitoring.view", "reports.view", "profile.view"],
  Auditor: ["dashboard.view", "routers.view", "configuration.view", "change.view", "backup.view", "monitoring.view", "security.view", "reports.view", "reports.export", "audit.view", "profile.view"],
  "Read Only User": ["dashboard.view", "routers.view", "monitoring.view", "reports.view", "profile.view"],
  Approver: ["dashboard.view", "routers.view", "configuration.view", "change.view", "change.approve", "change.reject", "reports.view", "audit.view", "profile.view"],
  "Operations Manager": ["dashboard.view", "routers.view", "routers.health.view", "change.view", "change.approve", "backup.view", "monitoring.view", "reports.view", "reports.export", "audit.view", "profile.view"]
};

export function hasPermission(userPermissions: readonly Permission[], permission: Permission) {
  return userPermissions.includes(permission);
}
